version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Radical.Windows"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/Radical.Windows.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
